### PR TITLE
Fix logpath causing start to hang & other issues along the way

### PR DESCRIPTION
**Pull request by addisonElliott**
Hello,

First of all, sorry for the large PR. I probably should have split them up and I'm happy to do so if you would like, but I was thinking it would be nice to introduce all of these small changes at once.

I have quite a bit of experience as a developer (C/C++, Python, etc) but am fairly new to NodeJS. I was introduced to NodeJS via [Parse](https://github.com/parse-community/parse-server). Parse has some issues with running tests on Windows, and part of it is due to mongodb-runner having issues. So I'm working my way backwards to fix issues to be able to develop on Windows!

With that in mind, feel free to let me know what you want me to change with this PR.

This all started when I ran into a bug (see bullet #1) when trying to port mongodb-runner from *mongodb-tools* to this library as @imlucas was wanting to do. I was able to successfully get it ported (using Promises), but I ran into the bug so I decided to fix it first. Once this is merged, I will continue onward with my mission.

If you have any other tasks/TODOs with this library, I would be happy to help if you'd like.

Below is a detailed list of changes made in this PR and why I did them.

# Changes
* Fix issue where starting standalone server with `logpath` specified will cause `Server.start()` to hang. Added test to demonstrate issue.
    * Issue occurs because `stdout` is parsed in `Server.start()` for "*waiting for connections*", which does not occur if `logpath` is set. Removed this part and rather just use the `waitForAvailable` function since it does the job nicely in my opinion.
* Update `waitForAvailable` function to use Promises rather than callbacks
    * Seems to be inline with the remainder of this library to use the *co* library and yields & Promises to implement asynchronous functions.
* Increment default `retryCount` for `waitForAvailable` so tests will pass on Linux (had issues on my machine where it would time out)
* Add `initialMs` option to `waitForAvailable` and wait a certain amount of time before attempting to connect to MongoDB server
    * The purpose of this is to supplement the removed searching `stdout` for certain text which has issues if `logpath` is set.
* Update .gitignore to ignore VS Code project-specific information as well as output.log*
    * The VS Code folder is used to store my launch configuration and other workspace specific stuff. I don't believe this should be included in the repository so I decided to ignore it.
    * `output.log*` addition is used to ignore output logs created from tests.
* Update replicaset and shards to perform operations in **parallel** rather than series when applicable. Since replicaset and shards contain multiple servers, there are certain things that can be done in parallel instead of series, such as starting the servers. This is fixed by calling yield on a list rather than one a time. The following functions are switched from series to parallel:
    1. *ReplSet*: start, stop, purge, arbiters, secondaries, passives
    2. *Sharded*: start
    3. *ConfigServer*: start, stop, purge, arbiters, secondaries
    * **Note:** A 3-member replicaset would take 2.5s to start in series but only takes 700ms with my changes on my machine. Thus, I believe this change is worthwhile to make!
* Add support for `protocolVersion` for replicaset to be set to 0/1 depending on MongoDB version. Currently, no `protocolVersion` is set and so it defaults to 0. From MongoDB 4.0+, this protocol is not valid and an error is thrown when running the tests (see below). Protocol version 1 is supported since MongoDB 3.2 and configuration servers require it be set. Fix this by allowing user to specify a `protocolVersion` field OR the `protocolVersion` is automatically set to 1 if the MongoDB version is 3.2+ or 4+.
* Fix failing Travis CI tests, had to do the following:
    * Bump Node engine to >=6 because prebuild-install used by kerberos required it
    * Updated yarn.lock
    * Updated Node version used to test TravisCI (4 -> 6)
```
MongoError: Support for replication protocol version 0 was removed in MongoDB 4.0. Downgrade to MongoDB version 3.6 and upgrade your protocol version to 1 before upgrading your MongoDB version
```
* Add spacing in certain spaces to stick with format of library and fix a few mistakes in comments
* Bump versions of packages
* Set one timeout for each tests file rather than for each individual test
* Change all test's bind_ip to **127.0.0.1** instead of **localhost**
    * Why you ask? Isn't this the same?! Well, there is a lovely "feature" on Windows where the DNS resolver takes a long time to resolve this. When testing, I discovered that it would take 1s for `executeCommand` to run on Windows and only 5ms on Linux. This was fixed by using 127.0.0.1 instead. Not a big deal, but shaves off some running time for tests on Windows.
* Include additional information when server fails or closes unexpectedly (include stdout)
* Fix issue with random build tests failing with error that mentions socket timeout in tests. This was due to the socket timeout for commands being set to 5s but the command taking longer to respond.
    * Made option to specify the connection timeout and/or socket timeout, otherwise they default to 5s and forever, respectively. Forever makes more sense for the socket timeout because you are already connected so you should expect a response from the server. However, I think the "forever" actually times out at 36s, which is set by mongodb-core package.
* Fixed a **different** issue with tests failing in Travis CI. This would cause servers to not startup because the address was already in use. My best guess for this (I spent a long time debugging), is that the tests failed before and the mongod/mongos processes were stuck being up. 
    * The solution I came up with was to use kill-mongodb to kill processes before tests begin. In addition, after each test, a hook is set to run that will kill all MongoDB instances. In the off chance that a test fails, usually all tests following that one will fail as well because the server is not closed. This solves this problem!

### CODE REVIEW

**Comment by mbroadst** [comment]
Hi @addisonElliott, wow thanks for the huge PR. A couple of comments, but also I think it's unlikely you'll be able to get a timely review with this many changes in a single PR. Could you possibly break them into something more manageable?

I'll leave some general notes here:

* We (the MongoDB node driver) continue to need to support Node v4 for the time being, so switching the default to Node v6, or switching to async/await is unfortunately not possible 
  * The issue with node 4 causing the failure on travis is because travis is using `yarn`, we should disable that rather than drop node 4 testing

* In general, the goal would be to completely remove `co` from this library in favor of promises (you can easily `async/await` this from the consumer side)

The rest of the changes seems non controversial, just would be easier to discuss in isolation. Thanks again for your contribution, I hope we can get most (if not all) of this merged in!

**Comment by mbroadst** [comment]
@addisonElliott the general rationale was to reduce the number of dependencies, but I only really feel 3/10 about this one 😄 As long as we consistently stick to one approach, I think using `co` is fine for now.

**Comment by addisonElliott** [comment]
@mbroadst I understand what you're saying. My opinion would be to wait until you can set the minimum node version to 8 and then convert to async/await. 

I've split this PR into multiple PRs (6 of them). I would start with #11 and then probably #15 because it also causes Travis CI tests to fail occasionally. From there, the remaining 4 PRs are independent of one another.

I'm happy to make changes and fix merge conflicts as they arise.

If you get a chance, I have a few other questions for you.
* Do all MongoDB packages need to work on Node v4? (In particular, I'm thinking runner, is-mongodb-running, kill-mongodb)
* I noticed mongodb-runner uses the package "eslint-config-mongodb-js" ([here](https://github.com/mongodb-js/runner/blob/master/package.json#L58)) while this library does not use that. Which method is preferred? (Similar thing with mongodb-js-precommit package)

**Comment by mbroadst** [comment]
Thanks for the PRs, here are the answers to your questions:
  - `runner`, `is-mongodb-running`, `kill-mongodb` are used for our "Compass" product, and are not related to this project per se. They do not have the same requirements we have on running on node v4.
  - This project should be using `prettier`, and the [eslint config from the driver](https://github.com/mongodb/node-mongodb-native/blob/master/.eslintrc). I can add this after we get through your PRs, so as to reduce the conflicts

**Pull request closed without merging**
